import * as cdk from 'aws-cdk-lib';
import { Construct } from 'constructs';
import { StorageStack } from './StorageStack';
import { DatabaseStack } from './DatabaseStack';
import { ApiStack } from './ApiStack';
import { AuthStack } from './AuthStack';
import { MediaProcessingStack } from './MediaProcessingStack';
import { ObservabilityStack } from './ObservabilityStack';
import { Config } from '../bin/config';

/**
 * Senior Strategy: The Application Stage.
 * Centralizes the environment configuration for the production stacks.
 */
export class StreamingAppStage extends cdk.Stage {
  public readonly appDistributionBucketName: cdk.CfnOutput;
  public readonly adminPortalBucketName: cdk.CfnOutput;
  public readonly viewerPortalBucketName: cdk.CfnOutput;
  public readonly distributionId: cdk.CfnOutput;
  public readonly apiUrl: cdk.CfnOutput;
  public readonly userPoolId: cdk.CfnOutput;
  public readonly webClientId: cdk.CfnOutput;

  constructor(scope: Construct, id: string, props?: cdk.StageProps) {
    super(scope, id, props);

    const env = {
      account: Config.account,
      region: Config.region
    };

    const storage = new StorageStack(this, 'StorageStack', { env });
    this.appDistributionBucketName = storage.node.findChild('AppDistributionBucketName') as cdk.CfnOutput;
    this.adminPortalBucketName = storage.node.findChild('AdminBucketName') as cdk.CfnOutput;
    this.viewerPortalBucketName = storage.node.findChild('ViewerBucketName') as cdk.CfnOutput;
    this.distributionId = storage.node.findChild('DistributionId') as cdk.CfnOutput;

    const database = new DatabaseStack(this, 'DatabaseStack', { env });

    const auth = new AuthStack(this, 'AuthStack', { env });
    this.userPoolId = auth.node.findChild('UserPoolId') as cdk.CfnOutput;
    this.webClientId = auth.node.findChild('WebClientId') as cdk.CfnOutput;

    const mediaProcessing = new MediaProcessingStack(this, 'MediaProcessingStack', {
      env,
      sourceBucket: storage.mediaBucket,
      thumbnailBucket: storage.thumbnailBucket,
      hlsBucket: storage.hlsBucket,
      metadataTable: database.table,
    });

    // Principal Strategy: Custom Domain Propagation to API Layer.
    // Ensure pre-signed and CDN video URLs generated by Scribe Lambda use the custom domain.
    const effectiveCdnDomain = Config.useCustomDomain && Config.domainName
      ? Config.domainName
      : storage.distribution.distributionDomainName;

    const api = new ApiStack(this, 'ApiStack', {
      env,
      table: database.table,
      userPool: auth.userPool,
      cdnDomain: effectiveCdnDomain,
      mediaBucket: storage.mediaBucket,
      orchestratorLambda: mediaProcessing.orchestratorLambda
    });
    this.apiUrl = api.node.findChild('ApiUrl') as cdk.CfnOutput;

    new ObservabilityStack(this, 'ObservabilityStack', {
      env,
      logGroup: api.logGroup
    });
  }
}
